name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/obsidian_deploy.yml
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}

